# Generated by Django 4.0.4 on 2022-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('reading_time', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='post/')),
            ],
        ),
    ]
